const moduloA = require('./moduloA')
const moduloB = require('./moduloB')
const moduloC = require('./moduloC')
const moduloTeste = require('./moduloTeste')
console.log(moduloA.ola)
console.log(moduloA.bemVindo)
console.log(moduloA.ateLogo)
console.log(moduloA)
console.log(moduloB.bomDia)
console.log(moduloB.boaNoite())
console.log(moduloB)
console.log(moduloC.soma(1, 3))
console.log(moduloTeste.mult(5, 5))